apiVersion: metallb.io/v1beta1 

kind: IPAddressPool 

metadata: 

  name: kong-pool 

  namespace: metallb-system 

spec: 

  addresses: 

  - 192.168.2.240/32 

 

--- 

apiVersion: metallb.io/v1beta1 

kind: L2Advertisement 

metadata: 

  name: kong-l2 

  namespace: metallb-system 

spec: {} 
